Src/Editor/Bin/Maps/Okopovo.cpp
Src/host/GameObjects/Structures/Constructions/Construction.sqf

Добавил новый обьект в шаблоны

---

Src/Editor/Bin/Maps/Saloon.cpp
Src/host/GameModes/Saloon/SaloonRoles.sqf
Src/host/MapManager/Maps/Saloon.sqf

- Добавил переулок;
- перевернул все стулья в баре;
- добавил комнату для спавна кухарей(поменять точки спавна нада);
- немного оьновил комнату барника;
- добавил сетку на барную стойку от вредителей.

Внёс изменения на карту Злачик

---

Src/client/ProxyItems/ConfigProxyItems.sqf
Src/host/GameObjects/Items/Bodyparts/Bodyparts.sqf
Src/host/GameObjects/Items/Clothes/cloth.sqf
Src/host/GameObjects/Items/Food/Foods/Food.sqf
Src/host/GameObjects/Items/RangedWeapons/AmmoBoxes.sqf
Src/host/GameObjects/Items/RangedWeapons/Magazines.sqf

Обновление моделей по задаче #115 
- Новые модели коробок патронов
- Новые модели магазинов
- Новые модели частей тела
- Новые модели еды
- Новая общая модель одежды

Добавлены новые модели игровых предметов

---

Src/host/GameModes/Dirtpit/BaseGamemode.sqf
Src/host/GameModes/Dirtpit/StationRoles.sqf
Src/host/GameModes/Saloon/GM_Saloon.sqf
Src/host/GameObjects/Items/Food/Foods/Food.sqf
Src/host/engine.hpp

Fix dev build 139115a (no changelogs)

---

Src/client/WidgetSystem/widget_init.sqf
Src/client/loader.hpp
Src/fn_init.sqf
Src/host/GameObjects/Items/Clothes/cloth.sqf

Стабильное обновление
- Исправление #164 
- Исправление #159

Stable - Common fixes

---

.github/workflows/sync_changelogs.yml
Src/Editor/Core/Core_io_helper.sqf
Src/Editor/Widgets/Menu_functions.sqf
Src/client/ClientStatistic/ClientStatistics_init.sqf
Src/client/ClientStatistic/DevbuildWidget_init.sqf
Src/host/GameModes/Dirtpit/StationRoles.sqf
Src/host/GamemodeManager/Gamemode_RoundManager.sqf
Src/host/engine.hpp

Dev to main

---

Src/Editor/Bin/Maps/Saloon.cpp
Src/host/MapManager/Maps/Saloon.sqf

- Вернул стол торговцу
- Изменил бандитов
- Добавил задний двор Бару

Доработка карты Злачник

---

Src/Editor/Bin/Maps/Saloon.cpp
Src/client/ClientData/SendCommand.sqf
Src/host/MapManager/Maps/Saloon.sqf

Общие фиксы
- Исправлено #181 
- Исправлено #179

Stable - Исправления командного меню и карты Злачника

---

Src/host/VerbSystem/verbsCondAndAct.sqf

Жрунов больше нельзя раздеть

---

Src/client/NetDisplays/Displays/Paper.sqf
Src/host/CommonComponents/!PreInit.sqf

Исправление ошибки по задаче и улучшение netdisplay для бумаги
- Исправление #190
- Новая функция - `stringReplace`
- Улучшение логики и работы дисплея записи на бумаге.

Исправлено отображение текста на бумаге

---

Src/host/GameObjects/Structures/Lighting/Natural.sqf

Исправление проблемы, описанной в #210

Исправлена ошибка, позволяющая подключать свечки к держателям для факела

---

Src/host/GameObjects/Mobs/Mob_Life.sqf

Ошибка не подтвердилась но проблема вероятнее всего из этого места
Решение проблемы, описанной в #193

Исправлена возможная ошибка синхронизации анимаций умерших или бессознательных персонажей

---

Src/client/Lobby/CharSettings.sqf
Src/client/Lobby/debug.sqf
Src/client/Lobby/lobbi_init.sqf
Src/host/GameObjects/Mobs/Mob.sqf
Src/host/GamemodeManager/Gamemode_RoundManager.sqf
Src/host/Namings/FaceList.sqf
Src/host/Namings/FacesHelpers.sqf
Src/host/Namings/PrepareFaces.sqf
Third-party/ImageConverter/optimize_paa.py

Минорное обновление системы лиц, включающее обновленное лобби, компонент лиц.
**Данное обновление требует последней версии мода Content**
- Решение #199 
- Добавлена утилита конвертации лиц
- Дефолтная униформа для женского персонажа теперь берется из `MobWoman::defaultUniform` вместо установки при заходе за роль.

Обновлена настройка лиц в лобби, 200+ мужских и 50+ женских лиц

---

Src/client/StrafeLock/StrafeLock_init.sqf
Src/client/WidgetSystem/blockedButtons.hpp
Src/client/WidgetSystem/functions.sqf
Src/client/loader.hpp
Src/host/CommonComponents/Animator.sqf
Src/host/GameObjects/Mobs/Mob.sqf
Src/host/GameObjects/Mobs/Mob_Events.sqf

Слияние дев ветки с мейном, включающее решение по задачи #214 и полезные общие функции для анимаций.
- Решение #214 
- Новые функции для проверки моба на ходьбу, бег, спринт.

Добавлена тестовая фича антистрейфа

---

Src/client/Lobby/SystemSettings.sqf

Добавлена новая категория основных страниц вики, доступных из лобби

---

Src/host/ClientManager/cmds/Common.sqf
Src/host/Discord/Accounts.sqf

Решение #236, улучшенный вывод при ошибке привязки
- #236

Исправлена ошибка с неверным токеном при привязке аккаунта

---

ReMaker/Client/description.ext

Исправлено открытие вики ссылок из лобби

---

Src/Editor/Bin/Maps/Minimap.cpp
Src/host/MapManager/Maps/Minimap.sqf

Поправил дверь в баре, теперь она открывается в правильную сторону и не мешает проходу

Фикс дверей в Грязноямске

---

Src/Editor/Bin/Maps/Truba.cpp
Src/host/GameModes/GMTruba/GMTruba_QuietShift.sqf
Src/host/MapManager/Maps/Truba.sqf

Минорные правки режима и карты.
- Исправлены ошибки на карте
- Изменён текст окончания раунда при смерти лидеров сторон

Доработка режима и карты Труба

---

Src/host/GameObjects/Mobs/Mob_Events.sqf

Убран стан при срабатывании антистрейфа

---

Src/Editor/Bin/Maps/Truba.cpp
Src/host/MapManager/Maps/Truba.sqf

Минорные правки карты.
- Исправлена ошибка с неправильными патронами на складе
- Добавлено несколько дополнительных предметов на склад
- Минорные изменения в районе перекрёстка и в пещерах

Доработка карты Труба

---

Src/client/ClientData/EscapeMenu.sqf
Src/client/ClientInit/ClientInit.sqf
Src/client/WidgetSystem/functions.sqf

Исправлена проверка яркости

---

Src/client/ClientInit/ClientInit.sqf

Исправление дистанции прорисовки

---

Src/Editor/SystemTools/LigthSimulation.sqf
Src/Editor/VisualComponents/ScriptedEmitterEditor.sqf
Src/Editor/VisualComponents/ScriptedEmitterEditor/ScriptedEmitterEditor_io.sqf

Фикс рендера при включенном предпросмотре освещения

Исправление предпросмотра частиц

---

Src/Editor/Core/Core_settings_preInit.sqf
Src/Editor/Simulation/Simulation_init.sqf
Src/host/ClientManager/cmds/EditorAndDebug.sqf
Src/host/GamemodeManager/GamemodeManager.sqf

Resolved #344

---

.gitignore

Стабильное обновление ReNode 1.7.33b8edc
- Информация о GUID-ах компиляции графов хранится в отдельном файле
- Улучшено отображение значений по умолчанию в окне свойств графа

ReNode 1.7.33b8edc

---

ReNode/Graphs/Dorm/GMDorm.graph
ReNode/Graphs/Dorm/Roles/RBasicRoleSpalnik.graph
ReNode/Graphs/Dorm/Roles/RLekarDorm.graph
ReNode/Graphs/Dorm/Roles/RMolDorm.graph
ReNode/Graphs/Dorm/Roles/RUchastDorm.graph
Src/Editor/Bin/Maps/Dorm.cpp
Src/host/MapManager/Maps/Dorm.sqf

Исправлены незначительные ошибки в режиме, ролях и карте.

Исправление ошибок для режима и карты Спальник

---

Src/host/GameObjects/Mobs/Mob_Life.sqf

Исправлена проблема с броском в случаи кода персонаж, который хочет что-то кинуть находится под воздействием веществ, подавляющих боль

Исправление проблемы с бросками предметов

---

Src/host/GameModes/BasicTask.sqf
Src/host/Logger/Logger_init.sqf

Этот запрос на слияние решает задачу: #385

Resolved #385

---

Src/client/ClientData/ClientData.sqf
Src/client/ClientData/ClientData_customAnims.sqf
Src/client/InputSystem/inputKeyHandlers.sqf
Src/host/CommonComponents/Replicator.sqf
Src/host/GameObjects/ConstantAndDefines/Mobs.h
Src/host/GameObjects/Interfaces/ISeat.Interface
Src/host/GameObjects/Mobs/BasicMob.sqf
Src/host/GameObjects/Mobs/Mob_Combat.sqf
Src/host/GameObjects/Mobs/Mob_Emotes.sqf
Src/host/GameObjects/Mobs/Mob_Events.sqf
Src/host/GameObjects/Mobs/Mob_Life.sqf
Src/host/VerbSystem/ActionsPseudonames.sqf

Этот PR реализовывает систему кастомных анимаций и решает проблему, описанную в #394

Кастомные анимации типа "сидя" и "стоя"

---

Src/host/GameObjects/Mobs/Mob_Emotes.sqf

Исправление последнего PR #398

Fixed logic

---

Src/host/GameObjects/Structures/Effects/Teleport.sqf

Fixed class sewercoverbase damage

---

Src/Editor/Bin/Maps/Detective.cpp
Src/Editor/Bin/Maps/Truba.cpp
Src/host/MapManager/Maps/Truba.sqf
Src/host/MapManager/Maps/detective.sqf

Подготовка карт Труба и Поместье для системы пожаров
- Исправлены проблемы которые позволяли возникнуть самопроизвольному пожару в начале раунда
- Добавлены умывальники и вёдра

Доработка карт Поместье и Труба для системы пожаров

---

Src/Editor/GameObjectsLibrary/GOLib_visual.sqf
Src/client/LightEngine/LightEngine.sqf
Src/client/LightEngine/ScriptedEffects.sqf

- Исправление #347 
- Исправлен режим предпросмотра освещения

Исправление редактора

---

Src/host/GameObjects/GameObject.sqf
Src/host/GameObjects/Items/Debris/Debris.sqf

- fix creating debris on destroy types of debris
- fix internal error on debris creating

Исправление системы осколков

---

ReNode/Graphs/Theatre/GMTheatre.graph
ReNode/Graphs/Theatre/RArtistGroup1Theatre.graph

- fixed runtime gamemode duration
- fixed random scenario for actors

common gamemode theatre fixes

---

ReNode/Graphs/ObjectScripts/SCR_TheatreButtonScenario.graph
Src/Editor/Bin/Maps/Theatre.cpp
Src/host/MapManager/Maps/Theatre.sqf

Минорные правки по театру.
- Поправлена логика скрипта SCR_TheatreButtonScenario
- Добавлены бумага и ручки владельцу театра и актеров.
- Добавлены сигареты

Правки режима и карты Театр

---

Src/Editor/Bin/Maps/Theatre.cpp
Src/host/GameObjects/GameObject.sqf
Src/host/GameObjects/Items/RangedWeapons/Ammo.sqf
Src/host/GameObjects/Items/RangedWeapons/AmmoBoxes.sqf
Src/host/GameObjects/Items/Traps/Trap.sqf
Src/host/MapManager/Maps/Theatre.sqf

- Холостые патроны
- Отключена возможность таскания заряженных капканов
- Патроны и магазины холостые в карте театра

Пререлизные фиксы

---

Src/Editor/Core/Core_init.sqf
Src/Editor/Editor_init.sqf
Src/Editor/GameObjectsInspector/Inspector_functions.sqf
Src/Editor/Widgets/Widget_ContextMenu.sqf

Можно создавать специальных мобов-манекенов.
ПКМ по миру -> Создать манекен
При ПКМ по манекену можно задать положение (сидя, стоя, лежа)

Resolved #478

---

Src/Editor/Core/Core_common.sqf
Src/Editor/Editor_init.sqf
Src/Editor/GameObjectsAssembly/GOAsm_batchProcessor.sqf
Src/Editor/GameObjectsAssembly/GOAsm_batch_structs.sqf
Src/Editor/GameObjectsAssembly/GOAsm_init.sqf
Src/Editor/Widgets/Widget_init.sqf
Src/host/GameModes/CommonGameAspects.sqf
Src/host/GameModes/Detective/GM_Detective.sqf
Src/host/GameObjects/Items/Chairs/ChairItems.sqf
Src/host/GameObjects/Structures/Furniture/Chairs.sqf
Src/host/struct.hpp

- Исправлено #496 
- Исправлено #492 
- Обновлён API для работы со структурами
- Добавлен тестовый пакетный обработчик (выключен, будет удален после обновления инспектора)
- Бамп версии удаления устаревших классов

Исправление ошибок, обновление версии редактора

---

Src/host/UnitTests/TestsCollection/math.sqf
Src/host/engine.hpp

Исправлена проблема верхнего предела макро-функции randInt

Исправление randInt

---

Src/Editor/Core/Core_init.sqf
Src/Editor/GameObjectsLibrary/GOLib_hashData.sqf
Src/Editor/SystemTools/GenerateItemIcons.sqf
Src/client/Inventory/PreviewObject.sqf
Src/client/Inventory/functions.sqf
Src/host/GameObjects/GameObject.sqf
Src/host/GameObjects/Mobs/Mob_Events.sqf
Src/host/GameObjects/Mobs/Mob_Inventory.sqf
Src/host/GameObjects/Structures/Containers/Container.sqf
Src/host/UnitTests/TestsCollection/math.sqf

Resolved #507
Partial fix task #434

Прикрепление бумаги на доски объявления

---

Src/host/CommonComponents/Structs/Profiling.sqf
Src/host/UnitTests/TestFramework.h
Src/host/UnitTests/TestsCollection/structs.sqf
Src/host/profiling.hpp

Struct-base profiler impl (#546)

---

Src/host/GamemodeManager/Gamemode_RoundManager.sqf

Отладочные сообщения назначенных игроков в разделе логирования игры

Resolved #572

---

ReNode/Graphs/Dorm/ObjectScripts/SCR_GuardButtonDorm.graph
ReNode/Graphs/Dorm/Roles/RRookieGuardDorm.graph
Src/Editor/Bin/Maps/Dorm.cpp
Src/host/MapManager/Maps/Dorm.sqf

- Исправлен таймер кнопки
- Исправлен навык "Винтовки" для роли "Ополченец"
- Добавлена еда для ополченцев
- Минорные правки по карте

Исправления после тестов для режима Спальник

---

Src/Editor/Bin/Maps/Dorm.cpp
Src/host/MapManager/Maps/Dorm.sqf

- Небольшие доработки карты в локации ополчения
- Исправлена проблема #577

Минорные правки карты Спальник

---

Src/Editor/Bin/Maps/Holiday.cpp
Src/host/GameObjects/Structures/Furniture/Sofas.sqf
Src/host/MapManager/Maps/Holiday.sqf

- Изменено расположение беседки
- Удалены прикуренные сигареты с карты
- Под усадьбу добавлена подложка из не горящих объектов
- Добавлены объекты во двор участкового
- Исправлена позиция сидения для Sofa01
- Жене участкового добавлена лекарская одежда
- В каждый дом добавлен алкоголь и курево
- Везде добавлена дополнительная посуда
- Добавлены различные сумки, чемоданы и мешки на карту
- Электричество во всём районе теперь нельзя отключить рубильником
- Мелкие правки карты

Фиксы и доработки карты режима Застолье в гостях

---

Src/Editor/Bin/Maps/Holiday.cpp
Src/host/MapManager/Maps/Holiday.sqf

Исправления карты "Рукав"

---

Src/host/CraftSystem/Crafts/Cooking.yml
Src/host/CraftSystem/Crafts/Medical.yml
Src/host/CraftSystem/Crafts/Others.yml

Добавлены требования к скиллам для нарезки масла
Крафт иголки с ниткой перенесён во вкладку "Медицина"

Маленькие изменения

---

Src/host/CraftSystem/Crafts/Cooking.yml
Src/host/CraftSystem/Crafts/Others.yml
Src/host/CraftSystem/Crafts/Weapons.yml
Src/host/LootSystem/Collections/BasicLoot/Things.yml

(+) Нарезка мельтешат
(+) Нарезка грибов
(+) Самокрутка

Изменения в крафтах

---

Src/host/GameObjects/Mobs/Mob_Interact.sqf

Reverts Relicta-Team/ReSDK_A3.vr#614

Revert "fixed interact distance"

---

Documentation/API/host/GamemodeManager.md
Src/host/Client/client.sqf
Src/host/GamemodeManager/GamemodeFunctions.sqf
Src/host/GamemodeManager/Gamemode_RoundManager.sqf

fixed https://github.com/Relicta-Team/ReSDK_A3.vr/issues/606

Stable - Исправление бага с валидацией роли
